"""empty message

Revision ID: 09d40f5a7029
Revises: 5475ef25d929
Create Date: 2026-01-29 18:42:05.639749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09d40f5a7029'
down_revision = '5475ef25d929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('comment_author_id_key', type_='unique')
        batch_op.create_foreign_key(None, 'user', ['author_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('comment_author_id_key', ['author_id'])
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###
