"""empty message

Revision ID: 541b3cdbb5bd
Revises: 09d40f5a7029
Create Date: 2026-01-29 18:53:37.494287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541b3cdbb5bd'
down_revision = '09d40f5a7029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
