"""empty message

Revision ID: 59f4ca45f158
Revises: bab60cc3e159
Create Date: 2026-01-29 19:52:27.685456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f4ca45f158'
down_revision = 'bab60cc3e159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('user_from_id', sa.Integer(), nullable=False),
    sa.Column('user_to_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_from_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_to_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_from_id', 'user_to_id')
    )
    op.drop_table('following')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('following',
    sa.Column('user_from_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_to_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_from_id'], ['user.id'], name='following_user_from_id_fkey'),
    sa.ForeignKeyConstraint(['user_to_id'], ['user.id'], name='following_user_to_id_fkey'),
    sa.PrimaryKeyConstraint('user_from_id', 'user_to_id', name='following_pkey')
    )
    op.drop_table('followers')
    # ### end Alembic commands ###
