"""empty message

Revision ID: c5d974d22272
Revises: 4117daa95848
Create Date: 2026-01-29 17:49:28.831704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5d974d22272'
down_revision = '4117daa95848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('following',
    sa.Column('user_from_id', sa.Integer(), nullable=False),
    sa.Column('user_to_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_from_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_to_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_from_id', 'user_to_id')
    )
    op.drop_table('followers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('user_from_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_to_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_from_id'], ['user.id'], name='followers_user_from_id_fkey'),
    sa.ForeignKeyConstraint(['user_to_id'], ['user.id'], name='followers_user_to_id_fkey'),
    sa.PrimaryKeyConstraint('user_from_id', 'user_to_id', name='followers_pkey')
    )
    op.drop_table('following')
    # ### end Alembic commands ###
